/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
// package chap4;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author LENOVO
 */
public class CountDownTimerGUI extends javax.swing.JFrame {

    int min, sec, hour, hour1, min1, sec1;
    Timer timer;
    boolean isStop = false;

    public CountDownTimerGUI() {
        initComponents();
        for (int i = 0; i < 60; i++) {
            if (i < 10) {
                cbxMin.addItem("0" + i);

            } else {
                cbxMin.addItem("" + i);
            }

        }
        for (int i = 0; i < 60; i++) {
//            cbxSec.addItem("" + i);
            if (i < 10) {
                cbxSec.addItem("0" + i);

            } else {
                cbxSec.addItem("" + i);
            }

        }

        for (int i = 0; i < 25; i++) {
            if (i < 10) {
                cbxHour.addItem("0" + i);

            } else {
                cbxHour.addItem("" + i);
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblMin = new javax.swing.JLabel();
        lblSec = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        cbxMin = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbxSec = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        lblHour = new javax.swing.JLabel();
        cbxHour = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        btn5min = new javax.swing.JButton();
        btn10min = new javax.swing.JButton();
        btn15min = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CreatBySolahudeen");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Count DownTimer BY Solahudeen");

        lblMin.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        lblMin.setForeground(new java.awt.Color(204, 0, 0));
        lblMin.setText("00");

        lblSec.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        lblSec.setForeground(new java.awt.Color(204, 0, 0));
        lblSec.setText("00");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText(":");

        btnStart.setBackground(new java.awt.Color(0, 0, 0));
        btnStart.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnStart.setForeground(new java.awt.Color(0, 153, 153));
        btnStart.setText("START");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnStop.setBackground(new java.awt.Color(0, 0, 0));
        btnStop.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnStop.setForeground(new java.awt.Color(0, 153, 153));
        btnStop.setText("STOP");
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        cbxMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMinActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("MINUTE");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("SECOND");

        cbxSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSecActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chap4/clock.png"))); // NOI18N

        lblHour.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        lblHour.setForeground(new java.awt.Color(204, 0, 0));
        lblHour.setText("00");

        cbxHour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxHourActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("HOUR");

        btn5min.setText("5 Minute");
        btn5min.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5minActionPerformed(evt);
            }
        });

        btn10min.setText("10 Minute");
        btn10min.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10minActionPerformed(evt);
            }
        });

        btn15min.setText("15 Minute");
        btn15min.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn15minActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblHour)
                                    .addComponent(cbxHour, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblMin)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4))
                                    .addComponent(cbxMin, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(cbxSec, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblSec)
                                        .addGap(38, 38, 38)
                                        .addComponent(jLabel7)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn5min, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn10min, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn15min)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnStart)
                                .addGap(83, 83, 83)
                                .addComponent(btnStop)
                                .addGap(74, 74, 74))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(174, 174, 174))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblSec)
                                .addComponent(lblMin)
                                .addComponent(jLabel4)
                                .addComponent(lblHour))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbxMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbxHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn5min)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn10min)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn15min)))
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStart)
                    .addComponent(btnStop))
                .addContainerGap(159, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        btnStart.setEnabled(false);
        timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (isStop) {
                    min = min1;
                    sec = sec1;
                    hour = hour1;
                    isStop = false;
                }
                if (sec == 0) {
                    sec = 60;
                    min--;
                }
                if (min < 0) {
                    min = 60;
                    min--;
                    hour--;
                }

                if (hour < 0) {
                    JOptionPane.showMessageDialog(rootPane, "TIMEOUTTTTT");
                    min = 0;
                    sec = 0;
                    hour = 0;
                    timer.stop();
                    btnStart.setEnabled(true);
//                    cbxHour.setEnabled(true);
//                    cbxMin.setEnabled(true);                    
//                    cbxSec.setEnabled(true);

                } else {
                    sec--;

                }
                if (sec < 10) {
                    lblSec.setText("0" + sec);
                } else {
                    lblSec.setText("" + sec);
                }
                if (min < 10) {
                    lblMin.setText("0" + min);
                } else {
                    lblMin.setText("" + min);
                }
                if (hour < 10) {
                    lblHour.setText("0" + hour);
                } else {
                    lblHour.setText("" + hour);
                }

//                lblMin.setText("" + min);
//                lblSec.setText("" + sec);
//                sec--;
//                lblSec.setText(""+sec);
            }
        });
        timer.start();

    }                                        

    private void cbxMinActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        lblMin.setText("" + cbxMin.getSelectedItem());
        min = Integer.parseInt(lblMin.getText());
    }                                      

    private void cbxSecActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        lblSec.setText("" + cbxSec.getSelectedItem());
        sec = Integer.parseInt(lblSec.getText());
    }                                      

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        min1 = min;
        sec1 = sec;
        hour1 = hour;
        isStop = true;
        timer.stop();
        btnStart.setEnabled(true);

    }                                       

    private void cbxHourActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        lblHour.setText("" + cbxHour.getSelectedItem());
        hour = Integer.parseInt(lblHour.getText());
    }                                       

    private void btn5minActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        int min5 = 5;
        lblMin.setText("0" + min5);
        min = Integer.parseInt(lblMin.getText());
    }                                       

    private void btn10minActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        int min10 = 10;
        lblMin.setText("" + min10);
        min = Integer.parseInt(lblMin.getText());
    }                                        

    private void btn15minActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        int min15 = 15;
        lblMin.setText("" + min15);
        min = Integer.parseInt(lblMin.getText());
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CountDownTimerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CountDownTimerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CountDownTimerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CountDownTimerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CountDownTimerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btn10min;
    private javax.swing.JButton btn15min;
    private javax.swing.JButton btn5min;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStop;
    private javax.swing.JComboBox<String> cbxHour;
    private javax.swing.JComboBox<String> cbxMin;
    private javax.swing.JComboBox<String> cbxSec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblHour;
    private javax.swing.JLabel lblMin;
    private javax.swing.JLabel lblSec;
    // End of variables declaration                   
}
